# Generated by Django 4.2.3 on 2023-07-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depnowAppMVC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('focus_hours_per_day', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('focus_hours', models.FloatField(default=0.0)),
                ('completion_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('settings', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depnowAppMVC.user'),
        ),
        migrations.AddField(
            model_name='tally',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depnowAppMVC.task'),
        ),
        migrations.AddField(
            model_name='tally',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depnowAppMVC.user'),
        ),
        migrations.AddField(
            model_name='streak',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depnowAppMVC.user'),
        ),
        migrations.AddField(
            model_name='focussession',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depnowAppMVC.task'),
        ),
        migrations.AddField(
            model_name='focussession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depnowAppMVC.user'),
        ),
    ]
