# Generated by Django 4.2.3 on 2023-11-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depnowAppMVC', '0005_remove_project_description_remove_project_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completion_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='focus_hours',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
