# Generated by Django 4.2.3 on 2023-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depnowAppMVC', '0006_remove_task_completion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
    ]
