# Generated by Django 4.2.3 on 2023-11-29 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depnowAppMVC', '0007_task_completion_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChatHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chatHistory', models.TextField()),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='depnowAppMVC.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
